sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
install:
  - pip install -r requirements.txt
script:
  - pylint src/azure_devtools
  - nosetests --with-coverage --cover-branches
after_success:
  - codecov
deploy:
  provider: pypi
  user: Laurent.Mazuel
  skip_upload_docs: true
  # password: use $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: '3.6'